version: '3'

services:
  postgres:
    build:
      dockerfile: DockerfilePostgre
    container_name: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - /postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pdd_exam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  api:
    container_name: 'telegram-bot-api'
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  client:
    container_name: 'telegram-bot-client'
    build:
      context: pathToDockerfile #your path to client's dockerfile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-rc-management
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      retries: 6
