version: '3'

services:
  postgres:
    build:
      context: ./
      dockerfile: DockerfilePostgres
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: 'telegram-bot-api'
    build:
      context: ./
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    links:
      - postgres

  frontend:
    container_name: 'telegram-bot-client'
    build:
      context: C:/Users/qWarn/IdeaProjects/PddExamBotClient/
      dockerfile: DockerfileFrontend
    ports:
      - "8081:8081"








