spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        show_sql:
        dialect:
  rabbitmq:
    port:
    host:


rabbitmq:
  exchange:
  queue:
  routingKey:

springdoc:
  swagger-ui:
    path:

server:
  error:
    include-message: always