spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        show_sql:
        dialect:
  kafka:
    bootstrap-servers:

kafka:
  topics:
    notificationTopic:

springdoc:
  swagger-ui:
    path: